apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-cloud-deployment
  namespace: dev
  labels:
    app: netflix-app-clone
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netflix-app-clone
  template:
    metadata:
      labels:
        app: netflix-app-clone
    spec:
      containers:
        - name: google-cloud-deployment
          image: rukevweubio/myclone-netflix-app:latest
          ports:
            - containerPort: 80
     
      
